name: Deploy Fullstack to Render with cicd

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.13.1'

    - name: Install dependencies and build frontend
      run: |
        cd frontend
        npm install
        npm run build
    
    - name: Run frontend tests (Vitest)
      run: |
        cd frontend
        npx vitest run

    - name: Install dependencies for backend
      run: |
        cd Backend
        npm install
    
    - name: Run backend tests (Jest)
      run: |
        cd Backend
        npm test
    
    - name: 🧪 Run Cypress E2E tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./frontend
        start: npm run preview
        wait-on: 'http://localhost:4173'
        browser: chrome

    - name: Deploy to Render
      if: success() # deploy only if tests pass
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        HOSTPORT: ${{ secrets.HOSTPORT }}
        ORIGIN: ${{ secrets.ORIGIN }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }} # Assuming this is the same as MONGO_URI
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
      run: |
        curl -X POST \
        -H 'Accept: application/vnd.api+json' \
        -H 'Authorization: Bearer $RENDER_API_KEY' \
        -H 'Content-Type: application/json' \
        -d '{"service_id":"srv-d0oe62adbo4c73b8pes0"}' \
        https://api.render.com/v1/services/srv-d0oe62adbo4c73b8pes0/deploys